apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-5587"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-5587"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-5587"
    spec:
      containers:
        - name: "aaaatiwarishubaks-5587"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaks5587"
          ports:
          - containerPort: 443