apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-5323"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-5323"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-5323"
    spec:
      containers:
        - name: "aaaatiwarishubaks-5323"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaks4927"
          ports:
          - containerPort: 80