apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaatiwarishubaks-8663"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaatiwarishubaks-8663"
  template:
    metadata:
      labels:
        app: "aaaatiwarishubaks-8663"
    spec:
      containers:
        - name: "aaaatiwarishubaks-8663"
          image: "aaaatiwarishubregistry.azurecr.io/aaaatiwarishubaks1e78"
          ports:
          - containerPort: 443