apiVersion: v1
kind: Service
metadata:
    name: "aaaatiwarishubaks-5587"
    labels:
        app: "aaaatiwarishubaks-5587"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "aaaatiwarishubaks-5587"