apiVersion: v1
kind: Service
metadata:
    name: "aaaatiwarishubaks-cd80"
    labels:
        app: "aaaatiwarishubaks-cd80"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "aaaatiwarishubaks-cd80"